name: Build

on:
  # push:
  workflow_dispatch: # 暫時設定為手動觸發，避免頻繁觸發 CI
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        # node-version: ["20.x", "22.x", "24.x"]
        node-version: ["22.x"]

      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Caches `~/.npm` folder

      - name: Install dependencies
        run: npm install

      - name: Install playwright
        run: npx playwright install

      - name: Build
        run: npm run build
